/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */
public final class addoldcustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
        
    PreparedStatement pst ;
    ResultSet rs;
     public String y ;
     public String check;
      public String datee;
      public  Calendar cal;
      public String pphone1;
      public String pphone2;
      public String ppp2;
      public String ppp1;
      public String ttt1;
      public String ttt2;
      String dayyy ;
      
      
    
   
    public addoldcustomer() throws ParseException {
        initComponents();
        

         clear();
        check="true";
        
           cal = new GregorianCalendar();
             
                int month=cal.get(Calendar.MONTH)+1;
             int year = cal.get(Calendar.YEAR);
                 int dayy =cal.get(Calendar.DAY_OF_MONTH);
             dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
           date1.setText(year+"-"+month+"-"+dayyy);
           datee=date1.getText().toString();
 
         name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         page.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         phone.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         address.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         p1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         p2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         d1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         d2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         t1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         t2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        page = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        p2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        d2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        d1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        visa = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cmvisa = new javax.swing.JComboBox();
        esalat = new javax.swing.JTextField();
        work = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setText("اسم العميل");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel10.setText("العنوان");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 80, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel12.setText("الصفحه");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, 30));

        page.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 70, 30));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 190, 30));

        save.setBackground(new java.awt.Color(156, 166, 187));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setText("حفظ");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel10.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 180, 40));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel14.setText("الضامن الاول");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 150, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel15.setText("رقم الضامن");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 120, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel17.setText("العنوان");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 80, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel18.setText("الضامن الثاني");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 150, -1));

        t2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 180, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel19.setText("رقم الضامن");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 120, -1));

        p2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 120, 30));

        d2.setColumns(20);
        d2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        d2.setRows(5);
        d2.setText("\n");
        jScrollPane2.setViewportView(d2);

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 270, 40));

        d1.setColumns(20);
        d1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        d1.setRows(5);
        d1.setText("\n");
        jScrollPane3.setViewportView(d1);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 270, 40));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 270, 40));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel20.setText("العنوان");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 80, -1));

        p1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 120, 30));

        t1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 180, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setText("رقم ثاني");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 90, 30));

        phone2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 190, 30));

        phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 120, 30));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel33.setText("رقم");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, 30));

        visa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, 30));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel30.setText("الوظيفة");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 110, -1, 30));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel31.setText("ايصالات");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel32.setText("النوع");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 80, 40));

        cmvisa.setEditable(true);
        cmvisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عادي", "فيزا" }));
        jPanel10.add(cmvisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, 30));

        esalat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(esalat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 50));

        work.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(work, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 170, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setText("رقم التليفون");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 120, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 270, 170));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 630, 370));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        serial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serial.setForeground(new java.awt.Color(255, 255, 255));
        serial.setText("Serial");
        jPanel10.add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 160, 40));

        date1.setText("date");
        jPanel10.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

       
           try {
               String namee = name.getText();
               String phonee = phone.getText();
               String phonee2 = phone2.getText();
               String adresss = address.getText();
               String pagee =page.getText();
               String tt1 = t1.getText();
               String tt2 = t2.getText();
               String dd1 = d1.getText();
               String dd2 =d2.getText();
               String pp1 = p1.getText();
               String pp2 = p1.getText();
               
               String sqll = "INSERT INTO hany.customer (type,visa,visanumber,date,esalat,work,phone2,"
                       + "name,phone,address,page, t1,t2,d1,d2,p1,p2) VALUES"
                       + " ('عادي','"+cmvisa.getSelectedItem().toString()+"',"
                       + "'"+visa.getText()+"','"+datee+"',"
                       + "'"+esalat.getText()+"','"+work.getText()+"',"
                       + "'"+phonee2+"','"+namee+"','"+phonee+"',"
                       + "'"+adresss+"','"+pagee+"','"+tt1+"',"
                       + "'"+tt2+"','"+dd1+"','"+dd2+"','"+pp1+"','"+pp2+"')";
               pst = (PreparedStatement)DBConnect.con.prepareStatement(sqll);
               pst.execute();
               clear();
           } catch (SQLException ex) {
               Logger.getLogger(addoldcustomer.class.getName()).log(Level.SEVERE, null, ex);
           }

              
                

    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox cmvisa;
    private javax.swing.JTextArea d1;
    private javax.swing.JTextArea d2;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField esalat;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField page;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField phone2;
    private javax.swing.JButton save;
    private javax.swing.JLabel serial;
    private javax.swing.JLabel serialid;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField visa;
    private javax.swing.JTextField work;
    // End of variables declaration//GEN-END:variables
public void clear()
{
    name.setText(""); 
    serialid.setText(""); 
 phone.setText("");
 address.setText("");
 page.setText("");
 t1.setText("");
 t2.setText("");  
 d1.setText("");
 d2.setText("");
 p1.setText("");
 p2.setText("");
 visa.setText("");
 page.setText("");
 esalat.setText("");
 phone2.setText("");
 work.setText("");
}
 
        
}
