/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author amnassar
 */

public class complete extends javax.swing.JFrame {
    PreparedStatement pst ;
    ResultSet rs;
    Home h ;
    public String datee ; 
    public  String dayOfWeek;
    public String fullname;
    String dayyy;
    
    
    public complete(String xx ) throws ParseException {
        initComponents();
        
        fullname=xx;
        completee();
          Calendar cal = new GregorianCalendar();  
          int month=cal.get(Calendar.MONTH)+1;
                int year = cal.get(Calendar.YEAR);
                int dayy =cal.get(Calendar.DAY_OF_MONTH);
             dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
           date1.setText(year+"-"+month+"-"+dayyy);
           datee=date1.getText().toString();
          
              
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        esalat = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cmvisa = new javax.swing.JComboBox();
        idnumber = new javax.swing.JTextField();
        page = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        idnumber1 = new javax.swing.JTextField();
        visa = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        d3 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        p3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        d2 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        p2 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        d1 = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        idnumber3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idnumber2 = new javax.swing.JTextField();
        work = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        esalat.setColumns(20);
        esalat.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        esalat.setRows(5);
        esalat.setText("\n");
        jScrollPane4.setViewportView(esalat);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 250, 50));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel31.setText("ايصالات");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 80, 30));

        save.setBackground(new java.awt.Color(138, 203, 195));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setText("تعديل");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 100, 50));

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel42.setText("العنوان");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 80, -1));

        phone2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, 30));

        t1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 180, 30));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 190, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel19.setText("رقم الضامن");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 120, 30));

        cmvisa.setEditable(true);
        cmvisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عادي", "فيزا" }));
        jPanel1.add(cmvisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 30));

        idnumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(idnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, 30));

        page.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 70, 30));

        phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 30));

        idnumber1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(idnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 120, 30));

        visa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, 30));

        d3.setColumns(20);
        d3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        d3.setRows(5);
        d3.setText("\n");
        jScrollPane5.setViewportView(d3);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 270, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel17.setText("العنوان");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 80, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel35.setText("رقم قومي");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 100, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel20.setText("العنوان");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 80, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel32.setText("النوع");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, 40));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel18.setText("الضامن2 ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 150, 30));

        p3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 120, 30));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 360, 70));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel40.setText("الضامن3 ");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 150, 30));

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel39.setText("رقم قومي");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 100, 30));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel38.setText("رقم قومي");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, 30));

        d2.setColumns(20);
        d2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        d2.setRows(5);
        d2.setText("\n");
        jScrollPane2.setViewportView(d2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 270, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel15.setText("رقم الضامن");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 120, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel14.setText("الضامن 1");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 140, -1));

        p2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, 30));

        p1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 120, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel10.setText("العنوان");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 80, -1));

        d1.setColumns(20);
        d1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        d1.setRows(5);
        d1.setText("\n");
        jScrollPane3.setViewportView(d1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 270, 40));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel37.setText("رقم قومي");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 100, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel12.setText("الصفحه");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 80, 30));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel41.setText("رقم الضامن");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 120, 30));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel33.setText("رقم");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, 30));

        t2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 180, 30));

        idnumber3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(idnumber3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 120, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setText("اسم العميل");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, -1, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setText("رقم ثاني");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 90, 30));

        idnumber2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(idnumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, 30));

        work.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(work, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 120, 30));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel30.setText("الوظيفة");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 30));

        t3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 180, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setText("رقم التليفون");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        date1.setText("jLabel2");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(977, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
                  
                     int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
                if(dialogResult == 0) {
                    try {
                        String idnumberr = idnumber.getText();
                String idnumberr1 = idnumber1.getText();
                String idnumberr2 = idnumber2.getText();
                String idnumberr3 =idnumber3.getText();
                String nameee = name.getText();
                String phoneee = phone.getText();
                String phonee2 = phone2.getText();
                String adressse = address.getText();
                String pagee =page.getText();
                String tt1e = t1.getText();
                String tt2e = t2.getText();
                String dd1e = d1.getText();
                String dd2e=d2.getText();
                String pp1e = p1.getText();
                String pp2e = p1.getText();
                String dd3e =d3.getText();
                String pp3e = p3.getText();
                String tt3e = t3.getText();
                String esalattt=esalat.getText();

                        String sql = "UPDATE hany.customer SET esalat='"+esalattt+"'"
                                + ",visanumber='"+visa.getText()+"',"
                                + "visa='"+cmvisa.getSelectedItem()+"', phone='"+phoneee+"',"
                                + " page='"+pagee+"',address='"+adressse+"',idnumber='"+idnumberr+"',"
                                + " t1='"+tt1e+"', t2='"+tt2e+"',idnumber1='"+idnumberr1+"',"
                                + " d1='"+dd1e+"', d2='"+dd2e+"', p1='"+pp1e+"',idnumber2='"+idnumberr2+"',"
                                + " t3='"+tt3e+"', d3='"+dd3e+"', p3='"+pp3e+"',idnumber3='"+idnumberr3+"',"
                                + " p2='"+pp2e+"',phone2='"+phone2.getText()+"',"
                                + "work='"+work.getText()+"'  WHERE name='"+fullname+"'";
                        pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "تم تعديل بيانات العميل بنجاح");
                        this.dispose();                     

                    } catch (SQLException ex) {
JOptionPane.showMessageDialog(rootPane, ex);
                    }
                }
                else
                {JOptionPane.showMessageDialog(this, " تم الغاء العمليه");

                }
                
                
               
              
        
           

    }//GEN-LAST:event_saveActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped

    }//GEN-LAST:event_nameKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox cmvisa;
    private javax.swing.JTextArea d1;
    private javax.swing.JTextArea d2;
    private javax.swing.JTextArea d3;
    private javax.swing.JLabel date1;
    private javax.swing.JTextArea esalat;
    private javax.swing.JTextField idnumber;
    private javax.swing.JTextField idnumber1;
    private javax.swing.JTextField idnumber2;
    private javax.swing.JTextField idnumber3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField name;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField page;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField phone2;
    private javax.swing.JButton save;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField visa;
    private javax.swing.JTextField work;
    // End of variables declaration//GEN-END:variables
      
public void completee()
{
     try {
             String sql="SELECT * FROM hany.customer where name='"+fullname+"'";
             pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                 name.setText(rs.getString("name"));
                 phone.setText(rs.getString("phone"));
                 address.setText(rs.getString("address"));
                 page.setText(rs.getString("page"));
                p1.setText(rs.getString("p1"));
                 p2.setText(rs.getString("p2"));
                 d1.setText(rs.getString("d1"));
                 d2.setText(rs.getString("d2"));
                 t1.setText(rs.getString("t1"));
                 t2.setText(rs.getString("t2"));
                 work.setText(rs.getString("work"));
                 esalat.setText(rs.getString("esalat"));
                 phone2.setText(rs.getString("phone2"));
                 visa.setText(rs.getString("visanumber"));
                 cmvisa.setSelectedItem(rs.getString("visa"));
                 d3.setText(rs.getString("d3"));
                 t3.setText(rs.getString("t3"));
                 p3.setText(rs.getString("p3"));
                 idnumber.setText(rs.getString("idnumber"));
                 idnumber1.setText(rs.getString("idnumber1"));
                 idnumber2.setText(rs.getString("idnumber2"));
                 idnumber3.setText(rs.getString("idnumber3"));
              }

         } catch (SQLException ex) {
             
         }
}
}
