/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author amnassar
 */

public class customerfollowup extends javax.swing.JFrame {
 
    PreparedStatement pst ;
    ResultSet rs;
    Home h ;
    public String date ; 
    public String msrofatt;
    public double total=0;
    String totalll;
    public double total2=0;
    public double total4=0;
    String dayyy;
    public double kash=0;
    
    
    public customerfollowup() {
        initComponents();
        
        Calendar cal = new GregorianCalendar();
 int dayy = cal.get(Calendar.DAY_OF_MONTH);
                int monthh=cal.get(Calendar.MONTH)+1;
                int yearr = cal.get(Calendar.YEAR);
                dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
                    month.setText(Integer.toString(monthh));
                year.setText(Integer.toString(yearr));
                 day2.setText(dayyy);
                 day.setText(dayyy);
                    month2.setText(Integer.toString(monthh));
                year2.setText(Integer.toString(yearr));
                 
            date1.setText(year+"-"+month+"-"+day);
           date=date1.getText().toString();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        s3 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        s4 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        year2 = new javax.swing.JTextField();
        s6 = new javax.swing.JLabel();
        month2 = new javax.swing.JTextField();
        s5 = new javax.swing.JLabel();
        day2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("من");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 50, -1));

        day.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 60, 30));

        s3.setBackground(new java.awt.Color(255, 255, 255));
        s3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s3.setForeground(new java.awt.Color(255, 255, 255));
        s3.setText("/");
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 10, -1));

        month.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 60, 30));

        s4.setBackground(new java.awt.Color(255, 255, 255));
        s4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s4.setForeground(new java.awt.Color(255, 255, 255));
        s4.setText("/");
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 10, -1));

        year.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 60, 30));

        year2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 30));

        s6.setBackground(new java.awt.Color(255, 255, 255));
        s6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.setText("/");
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 10, -1));

        month2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(month2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 60, 30));

        s5.setBackground(new java.awt.Color(255, 255, 255));
        s5.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setText("/");
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 10, -1));

        day2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(day2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 60, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("الي");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 50, -1));

        save.setBackground(new java.awt.Color(98, 113, 146));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("الايرادات اليومية");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/64586a0ad51dc03.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 250));

        date1.setText("jLabel2");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(464, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        total2=0;
        total=0;
        total4=0;
        kash=0;
        kashh();
           msrofat();
           mokdmat();
           mokdmat2();
           System.out.print(total2);
          //  String from=year1.getText()+"-"+month1.getText()+"-"+day1.getText();
            String from=year.getText()+"-"+month.getText()+"-"+day.getText();
            String to=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
            //String hitchott=Integer.toString(total);
           date=date1.getText().toString();
            InputStream in=null;
            try {
                
                in = this.getClass().getResourceAsStream("/reports/followup.jasper");
                String reportpath= "\\\\192.168.1.15\\sadam\\followup.jasper";
                Map<String,Object> para = new HashMap<String,Object>();
                para.put("date", from);
                para.put("from", from);
                para.put("to", to);
                para.put("mokdmat", total2);
                para.put("z", total);
                para.put("kash", kash);
                 JasperPrint j = JasperFillManager.fillReport(in, para,DBConnect.con);
                JasperViewer.viewReport(j,false);
            }
            catch (JRException ex) {
               JOptionPane.showMessageDialog(null, ex);
            } finally {
            }
        

    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date1;
    public javax.swing.JTextField day;
    public javax.swing.JTextField day2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField month;
    public javax.swing.JTextField month2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JButton save;
    public javax.swing.JTextField year;
    public javax.swing.JTextField year2;
    // End of variables declaration//GEN-END:variables
      public void msrofat()
      {
    try {
        String from1=year.getText()+"-"+month.getText()+"-"+day.getText();
        String from2=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
        String sqll="SELECT amount  FROM hany.msrofat where  kind='درج' and date between '"+from1+"' and '"+from2+"'";
        pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);
        rs=pst.executeQuery();
        while(rs.next()){
            try {
                double n = Double.parseDouble(rs.getString("amount"));
                total=total+n;
            } catch (SQLException ex) {
                Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    } catch (SQLException ex) {
        Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
    }
      }
       public void mokdmat()
      {
    try {
        String from1=year.getText()+"-"+month.getText()+"-"+day.getText();
        String from2=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
        String sqll="SELECT dailyprice FROM hany.logs where date between '"+from1+"' and '"+from2+"'  and type='مقدم' ";
        pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);
        rs=pst.executeQuery();
        while(rs.next()){
            try {
                String k=rs.getString("dailyprice");
                double n = Double.parseDouble(k);
                total2=total2+n;
            } catch (SQLException ex) {
                Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    } catch (SQLException ex) {
        Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
    }
      }
      
      public void mokdmat2()
      {
    try {
        String from1=year.getText()+"-"+month.getText()+"-"+day.getText();
        String from2=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
        String sqll="SELECT dailyprice FROM hany.logs where date between '"+from1+"' and '"+from2+"'  and type='مقدم' ";
        pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);
        rs=pst.executeQuery();
        while(rs.next()){
            try {
                String k=rs.getString("dailyprice");
                double n = Double.parseDouble(k);
                total4=total4+n;
            } catch (SQLException ex) {
                Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    } catch (SQLException ex) {
        Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
    }
      }
      
      public void kashh()
      {
    try {
        String from1=year.getText()+"-"+month.getText()+"-"+day.getText();
        String from2=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
        String sqll="SELECT total FROM hany.sell where date between '"+from1+"' and '"+from2+"'  ";
        pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);
        rs=pst.executeQuery();
        while(rs.next()){
            try {
                String k=rs.getString("total");
                double n = Double.parseDouble(k);
                kash=kash+n;
            } catch (SQLException ex) {
                Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
    } catch (SQLException ex) {
        Logger.getLogger(customerfollowup.class.getName()).log(Level.SEVERE, null, ex);
    }
      }
     
      
}
