/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author amnassar
 */
public final class editcustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
        
    PreparedStatement pst ;
    ResultSet rs;
     public String y ;
    
   
    public editcustomer() {
        initComponents();
        
         clear();
         tablelord();
         name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         page.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         phone.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         address.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         p1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         p2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         d1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         d2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         t1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         t2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        
          
            TableCellRenderer rendererFromHeader = tdetails.getTableHeader().getDefaultRenderer();
JLabel headerLabel = (JLabel) rendererFromHeader;
headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tdetails.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(6).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(7).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(8).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(9).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(10).setCellRenderer( centerRenderer );
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        mhna = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        page = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        visa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        p2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        save3 = new javax.swing.JButton();
        d2 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cmvisa = new javax.swing.JComboBox();
        d1 = new javax.swing.JTextField();
        save2 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdetails.setBackground(new java.awt.Color(138, 203, 195));
        tdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "d2", "d1", "p2", "p1", "t2", "t1", "عنوان العميل", "رقم الصفحه", "رقم العميل", "اسم العميل", "الرقم التسلسلي"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(0).setMinWidth(1);
            tdetails.getColumnModel().getColumn(0).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(0).setMaxWidth(1);
            tdetails.getColumnModel().getColumn(1).setMinWidth(1);
            tdetails.getColumnModel().getColumn(1).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(1).setMaxWidth(1);
            tdetails.getColumnModel().getColumn(2).setMinWidth(1);
            tdetails.getColumnModel().getColumn(2).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(2).setMaxWidth(1);
            tdetails.getColumnModel().getColumn(3).setMinWidth(1);
            tdetails.getColumnModel().getColumn(3).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(3).setMaxWidth(1);
            tdetails.getColumnModel().getColumn(4).setMinWidth(1);
            tdetails.getColumnModel().getColumn(4).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(4).setMaxWidth(1);
            tdetails.getColumnModel().getColumn(5).setMinWidth(1);
            tdetails.getColumnModel().getColumn(5).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(5).setMaxWidth(1);
            tdetails.getColumnModel().getColumn(7).setMinWidth(100);
            tdetails.getColumnModel().getColumn(7).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(7).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(8).setMinWidth(200);
            tdetails.getColumnModel().getColumn(8).setPreferredWidth(200);
            tdetails.getColumnModel().getColumn(8).setMaxWidth(200);
            tdetails.getColumnModel().getColumn(9).setMinWidth(270);
            tdetails.getColumnModel().getColumn(9).setPreferredWidth(270);
            tdetails.getColumnModel().getColumn(9).setMaxWidth(270);
            tdetails.getColumnModel().getColumn(10).setMinWidth(1);
            tdetails.getColumnModel().getColumn(10).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(10).setMaxWidth(1);
        }

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 920, 190));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setText("اسم العميل");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel21.setText("المهنه");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, 30));

        mhna.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(mhna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel10.setText("العنوان");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 80, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel12.setText("الصفحه");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 80, 30));

        page.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 70, 30));

        address.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 290, 30));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 190, 30));

        save.setBackground(new java.awt.Color(138, 203, 195));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setText("حفظ");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel10.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 180, 40));

        visa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(visa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 160, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel14.setText("الضامن الاول");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 150, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel15.setText("رقم الضامن");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 120, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel17.setText("العنوان");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 80, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel18.setText("الضامن الثاني");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 150, -1));

        t2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 180, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel19.setText("رقم الضامن");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 120, -1));

        p2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 120, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel20.setText("العنوان");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 80, -1));

        save3.setBackground(new java.awt.Color(138, 203, 195));
        save3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save3.setText("تقرير");
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });
        jPanel10.add(save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 150, 60));

        d2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 290, 30));

        p1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 120, 30));

        t1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 180, 30));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel33.setText("رقم الفيزا");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel32.setText("النوع");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 80, -1));

        cmvisa.setEditable(true);
        cmvisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "عادي", "فيزا" }));
        jPanel10.add(cmvisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 30));

        d1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 290, 30));

        save2.setBackground(new java.awt.Color(138, 203, 195));
        save2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save2.setText("تفريغ");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });
        jPanel10.add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 180, 40));

        save1.setBackground(new java.awt.Color(138, 203, 195));
        save1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save1.setText("بحث");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel10.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 180, 40));

        phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setText("رقم التليفون");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 120, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
                String namee = name.getText();
                String phonee = phone.getText();
                String adresss = address.getText();
                String pagee =page.getText();
                String tt1 = t1.getText();
                String tt2 = t2.getText();
                String dd1 = d1.getText();
                String dd2 =d2.getText();
                String pp1 = p1.getText();
                String pp2 = p1.getText();
                     int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
                if(dialogResult == 0) {
                    try {
                        String nameee = name.getText();
                String phoneee = phone.getText();
                String adressse = address.getText();
                String pageee =page.getText();
                String tt1e = t1.getText();
                String tt2e = t2.getText();
                String dd1e = d1.getText();
                String dd2e =d2.getText();
                String pp1e = p1.getText();
                String pp2e= p1.getText();

                        String sql = "UPDATE hany.customer SET name='"+nameee+"', phone='"+phoneee+"', page='"+pagee+"',address='"+adressse+"', t1='"+tt1e+"', t2='"+tt2e+"',"
                                + " d1='"+dd1e+"', d2='"+dd2e+"', p1='"+pp1e+"', p2='"+pp2e+"'  WHERE id='"+serialid.getText()+"'";
                        pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "تم تعديل بيانات العميل بنجاح");
                        clear();
                       tablelord();

                    } catch (SQLException ex) {

                    }
                }
                else
                {JOptionPane.showMessageDialog(this, " تم الغاء العمليه");

                }
                
                
               
              
                

    }//GEN-LAST:event_saveActionPerformed

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel =(DefaultTableModel)tdetails.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex=tdetails.getSelectedRow();
       serialid.setText(tmodel.getValueAt(selectrowindex, 10).toString());
        name.setText(tmodel.getValueAt(selectrowindex, 9).toString());
         phone.setText(tmodel.getValueAt(selectrowindex, 8).toString());
         page.setText(tmodel.getValueAt(selectrowindex, 7).toString());
        address.setText(tmodel.getValueAt(selectrowindex, 6).toString());
         t1.setText(tmodel.getValueAt(selectrowindex, 5).toString());
         t2.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        p1.setText(tmodel.getValueAt(selectrowindex, 3).toString());
         p2.setText(tmodel.getValueAt(selectrowindex, 2).toString());
          d1.setText(tmodel.getValueAt(selectrowindex, 1).toString());
         d2.setText(tmodel.getValueAt(selectrowindex, 0).toString());
       
    
  
    }//GEN-LAST:event_tdetailsMouseClicked

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed

        String namee = name.getText();
                String phonee = phone.getText();
                String adresss = address.getText();
                String pagee =page.getText();
                String tt1 = t1.getText();
                String tt2 = t2.getText();
                String dd1 = d1.getText();
                String dd2 =d2.getText();
                String pp1 = p1.getText();
                String pp2 = p1.getText();
                

        try {
            String sqll = "SELECT id,name,phone,page,address,t1,t2,p1,p2,d1,d2 FROM hany.customer WHERE  1=1 ";
            if(!name.getText().trim().isEmpty())
            {
                sqll=sqll+" AND name LIKE '%"+namee+"%'";
            }
            else if (!phone.getText().trim().isEmpty())
            {
                sqll=sqll+" AND phone LIKE '%"+phonee+"%'";
            }
            else if (!address.getText().trim().isEmpty())
            {
                sqll=sqll+" AND address LIKE '%"+adresss+"%'";
            }
             else if (!visa.getText().trim().isEmpty())
            {
                sqll=sqll+" AND visanumber LIKE '%"+visa.getText()+"%'";
            }
             else if (!mhna.getText().trim().isEmpty())
            {
                sqll=sqll+" AND work LIKE '%"+mhna.getText()+"%'";
            }
            else if (!page.getText().trim().isEmpty())
            {
                sqll=sqll+" AND page Like '%"+pagee+"%'";
            }
            else if (!t1.getText().trim().isEmpty())
            {
                sqll=sqll+" AND t1 Like '%"+tt1+"%'";
            } else if (!t2.getText().trim().isEmpty())
            {
                sqll=sqll+" AND t2 Like '%"+tt2+"%'";
            } else if (!d1.getText().trim().isEmpty())
            {
                sqll=sqll+" AND d1 Like '%"+dd1+"%'";
            } else if (!d2.getText().trim().isEmpty())
            {
                sqll=sqll+" AND d2 Like '%"+dd2+"%'";
            } else if (!p1.getText().trim().isEmpty())
            {
                sqll=sqll+" AND p1 Like '%"+pp1+"%'";
            }else if (!p2.getText().trim().isEmpty())
            {
                sqll=sqll+" AND p2 Like '%"+pp2+"%'";
            }
            
            pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails.getModel();
            model.setRowCount(0);
            int k = 0 ;
             while (rs.next())
                {
                    Object row[] = {
                      rs.getString("d2"),
                         rs.getString("d1"),
                       rs.getString("p2"),
                       rs.getString("p1"),
                      rs.getString("t2"),
                         rs.getString("t1"),
                       rs.getString("address"),
                        rs.getString("page"),
                      rs.getString("phone"),
                         rs.getString("name"),
                       rs.getString("id"),
                 
                                };
                    model.addRow(row);
                    k++;
                }
            for(int i = k ;i<11;i++)
            {
                Object rowData[] = {
                    "",
                    "",
                    "",
                    "",
                    "",
                };
                model.addRow(rowData);
            }
        }
        catch (SQLException ex) {
        }

    }//GEN-LAST:event_save1ActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        clear();
        tablelord();
    }//GEN-LAST:event_save2ActionPerformed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed
 
        if(name.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "اختر العميل");
        }
        else
        {
        InputStream in=null;
        try {
            String namee =name.getText().toString() ;
            in = this.getClass().getResourceAsStream("/reports/cart.jasper");
            String reportpath= "\\\\192.168.1.15\\sadam\\cart.jasper";
            Map<String,Object> para = new HashMap<String,Object>();
            para.put("name", namee);
            JasperPrint j = JasperFillManager.fillReport(in, para,DBConnect.con);
            JasperViewer.viewReport(j,false);
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(null,ex);
        } finally {

        }}

    }//GEN-LAST:event_save3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JComboBox cmvisa;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mhna;
    private javax.swing.JTextField name;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField page;
    private javax.swing.JTextField phone;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    private javax.swing.JButton save2;
    private javax.swing.JButton save3;
    private javax.swing.JLabel serialid;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tdetails;
    private javax.swing.JTextField visa;
    // End of variables declaration//GEN-END:variables
public void clear()
{
    name.setText(""); 
    serialid.setText(""); 
 phone.setText("");
 address.setText("");
 page.setText("");
 t1.setText("");
 t2.setText("");  
 d1.setText("");
 d2.setText("");
 p1.setText("");
 p2.setText("");
}
public void tablelord()
{
    try {
           String sqll = "SELECT * FROM hany.customer";
              pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails.getModel(); 
                model.setRowCount(0);
              int k = 0;
                while (rs.next())
                {
                    Object row[] = {
                      rs.getString("d2"),
                         rs.getString("d1"),
                       rs.getString("p2"),
                       rs.getString("p1"),
                      rs.getString("t2"),
                         rs.getString("t1"),
                       rs.getString("address"),
                        rs.getString("page"),
                      rs.getString("phone"),
                         rs.getString("name"),
                       rs.getString("id"),
                 
                                };
                    model.addRow(row);
                    k++;
                }
                for(int i = k ;i<11;i++)
                {
                 Object rowData[] = {
                       "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                       };
                model.addRow(rowData);
                } 
        }
        catch (SQLException ex) {
            
        }
}
     
}
