/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */
public final class item extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
        
    PreparedStatement pst ;
    ResultSet rs;
     public String y ;
     public String datee;
      public  Calendar cal;
      String dayyy;
   
    public item() throws ParseException {
        initComponents();
        
        cal = new GregorianCalendar();
             int dayy =cal.get(Calendar.DAY_OF_MONTH);
             dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
                int month=cal.get(Calendar.MONTH)+1;
                int year = cal.get(Calendar.YEAR);
       /* String dateString = String.format("%d-%d-%d", year, month, dayyy);
           java.util.Date date = new SimpleDateFormat("yyyy-M-dd").parse(dateString);*/
           date1.setText(year+"-"+month+"-"+dayyy);
           datee=date1.getText().toString();
           number.setText("");
           datees();
         clear();
         comboxfromcombo3();
         comboxfromcombo2();
         AutoCompleteDecorator.decorate(cmitem);
         items();
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cmitem = new javax.swing.JComboBox();
        number = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmdate = new javax.swing.JComboBox();
        save1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmitem2 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        gomla = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel22.setText("المنتج");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 80, -1));

        cmitem.setEditable(true);
        cmitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel10.add(cmitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 260, 30));

        number.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        number.setText("B");
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        jPanel10.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 70, 30));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel23.setText("الصفحة");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 80, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel14.setText("اليوم");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 60, -1));

        cmdate.setEditable(true);
        cmdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmdate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel10.add(cmdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 260, 30));

        save1.setBackground(new java.awt.Color(138, 203, 195));
        save1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save1.setText("بحث");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel10.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 90, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setText("المنتج");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 370, 60, -1));

        cmitem2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmitem2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jPanel10.add(cmitem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 260, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel17.setText("القيمة");
        jPanel10.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 60, 30));

        delete.setBackground(new java.awt.Color(138, 203, 195));
        delete.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("مسح");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel10.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 180, 50));

        amount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel10.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 70, 30));

        gomla.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(gomla, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 90, 40));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel25.setText("سعر الجمله");
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 130, 50));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel24.setText("السعر");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 80, 30));

        price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel10.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 90, 40));

        save.setBackground(new java.awt.Color(138, 203, 195));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setText("حفظ");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel10.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 180, 40));

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 720, 280));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        date1.setText("jLabel1");
        jPanel10.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       
        try
        {
             String itemm=cmitem.getSelectedItem().toString();
              int pricee = Integer.parseInt(price.getText());
              int gomlaa = Integer.parseInt(gomla.getText());
              String numberr=number.getText();
              int total = (pricee-gomlaa);
              if( price.getText().trim().isEmpty()||gomla.getText().trim().isEmpty() ||
                      cmitem.getSelectedItem().toString().trim().isEmpty()||number.getText().trim().isEmpty() )
            {
                JOptionPane.showMessageDialog(this, " من فضلك ادخل البيانات كاملة");
            }
            else
            {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
                if(dialogResult == 0) {
                    try{
                        String sql = "INSERT INTO hany.profit (item,gomla,price,page,total,date) VALUES"
                        + " ('"+itemm+"','"+gomlaa+"','"+pricee+"','"+numberr+"','"+total+"','"+datee+"')";
                        pst = (PreparedStatement)DBConnect.con.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "تم اضافه العملية بنجاح");
                       clear();
                        

                    }
                    catch(Exception e ){
                        JOptionPane.showMessageDialog(null, e);
                    }

                }
                else
                {JOptionPane.showMessageDialog(this, " تم الغاء العمليه");

                }

            }
        }
        catch(Exception ex)
        {
            
        }

    }//GEN-LAST:event_saveActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        
    }//GEN-LAST:event_priceActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed

        try

        {

            String sqll="SELECT item FROM hany.profit where 1=1 ";

            pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);

            rs=pst.executeQuery();

            while(rs.next()){

                String name = rs.getString("item");

                cmitem2.removeItem(name);

            }

        }

        catch(Exception ex)

        {
            JOptionPane.showMessageDialog(null,ex);
        }

        try {
            String namee=cmdate.getSelectedItem().toString();

            String sql="SELECT item  FROM hany.profit where  1=1 ";

            if(!cmdate.getSelectedItem().toString().trim().isEmpty())

            {

                sql=sql+" AND date ='"+namee+"'";

            }

            pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);

            rs=pst.executeQuery();

            while(rs.next()){

                String name = rs.getString("item");

                cmitem2.addItem(name);

            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null,ex);

        }
    }//GEN-LAST:event_save1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        try {
            String sql = "DELETE FROM hany.profit WHERE price='"+amount.getText()+"' "
                    + "and item='"+cmitem2.getSelectedItem().toString()+"'"
                    + " and date = '"+cmdate.getSelectedItem().toString()+"'";
            pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, " تم ازاله المصروف بنجاح");
            cmdate.setSelectedIndex(0);
            cmitem2.setSelectedIndex(0);
            amount.setText("");
        } catch (SQLException ex) {

        }

    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox cmdate;
    private javax.swing.JComboBox cmitem;
    private javax.swing.JComboBox cmitem2;
    private javax.swing.JLabel date1;
    private javax.swing.JButton delete;
    private javax.swing.JTextField gomla;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JTextField number;
    private javax.swing.JTextField price;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    private javax.swing.JLabel serialid;
    // End of variables declaration//GEN-END:variables
public void clear()
{
    cmitem.setSelectedIndex(0);
    serialid.setText(""); 
    price.setText("");
    gomla.setText("");
    number.setText("");
}
  public void items()
   {
        try {
             String sql="SELECT name  FROM hany.item order by name ";
             pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                String name = rs.getString("name");
                
                cmitem.addItem(name);
  
             }

         } catch (SQLException ex) {
             
         }
   }
  public void comboxfromcombo2()
      {
                   cmitem.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                JComboBox cmitemm = (JComboBox) event.getSource();

                Object item = event.getItem();
                
                 try {
             String sql="SELECT * FROM hany.profit where item='"+cmitem.getSelectedItem().toString()+"'  ";
             pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
             rs=pst.executeQuery();
             if(rs.next()){
                 gomla.setText(rs.getString("gomla"));
                 price.setText(rs.getString("price"));
                 
                 
              
              }

         } catch (SQLException ex) {
             
         }
         }
        });
       
      }
  
  public void comboxfromcombo3()
      {
                   cmitem2.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                JComboBox cmitemm = (JComboBox) event.getSource();

                Object item = event.getItem();
                
                 try {
             String sql="SELECT * FROM hany.profit where date='"+cmdate.getSelectedItem().toString()+"' and item='"+cmitem2.getSelectedItem().toString()+"'  ";
             pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
             rs=pst.executeQuery();
             if(rs.next()){
                 amount.setText(rs.getString("price"));
                 
                 
                 
              
              }

         } catch (SQLException ex) {
             
         }
         }
        });
       
      }
      public void datees()
   {
        try {
             String sql="SELECT distinct date  FROM hany.profit order by CAST(date AS DATE)  ";
             pst=(PreparedStatement) DBConnect.con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                String name = rs.getString("date");
                
                cmdate.addItem(name);
  
             }

         } catch (SQLException ex) {
             
         }
   }
}
