/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author amnassar
 */

public class latedayperweek extends javax.swing.JFrame {
 
    PreparedStatement pst ;
    ResultSet rs;
    Home h ;
    public String datee ; 
    public  String dayOfWeek;
    
    
    public latedayperweek() throws ParseException {
        initComponents();
        
         Calendar cal = new GregorianCalendar();
             int day = cal.get(Calendar.DAY_OF_MONTH);
                int month=cal.get(Calendar.MONTH)+1;
                int year = cal.get(Calendar.YEAR);
         
           date1.setText(year+"-"+month+"-"+day);
           datee=date1.getText().toString();
          
                int monthh=cal.get(Calendar.MONTH)+1;
                int yearr = cal.get(Calendar.YEAR);
                day1.setText(Integer.toString(day));
                    month1.setText(Integer.toString(monthh));
                year1.setText(Integer.toString(yearr));
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        day1 = new javax.swing.JTextField();
        month1 = new javax.swing.JTextField();
        year1 = new javax.swing.JTextField();
        s5 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        s8 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        s9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        day1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(day1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 60, 30));

        month1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(month1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, 30));

        year1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 60, 30));

        s5.setBackground(new java.awt.Color(255, 255, 255));
        s5.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s5.setForeground(new java.awt.Color(255, 255, 255));
        s5.setText("سنه");
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 60, -1));

        s6.setBackground(new java.awt.Color(255, 255, 255));
        s6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s6.setForeground(new java.awt.Color(255, 255, 255));
        s6.setText("شهر");
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, -1));

        a3.setBackground(new java.awt.Color(255, 255, 255));
        a3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setText("يوم ");
        jPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 60, -1));

        s8.setBackground(new java.awt.Color(255, 255, 255));
        s8.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s8.setForeground(new java.awt.Color(255, 255, 255));
        s8.setText("/");
        jPanel1.add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 10, -1));

        save.setBackground(new java.awt.Color(98, 113, 146));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("مستحقات اليوم السابق بالاسبوع");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 300, 40));

        s9.setBackground(new java.awt.Color(255, 255, 255));
        s9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s9.setForeground(new java.awt.Color(255, 255, 255));
        s9.setText("/");
        jPanel1.add(s9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 10, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/64586a0ad51dc03.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 260));

        date1.setText("jLabel2");
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(474, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        
            try {                                     
                
                int year = Integer.parseInt(year1.getText());
                int month =Integer.parseInt(month1.getText());
                int day   =  Integer.parseInt(day1.getText());
                String from=year1.getText()+"-"+month1.getText()+"-"+day1.getText();
                String dayy=day1.getText();
                String dateString = String.format("%d-%d-%d", year, month, day);
                java.util.Date date = new SimpleDateFormat("yyyy-M-d").parse(dateString);
                dayOfWeek = new SimpleDateFormat("EEEE", Locale.ENGLISH).format(date);
                InputStream in=null;
                try {
                    in = this.getClass().getResourceAsStream("/reports/lateamountPerWeek.jasper");
                    String reportpath= "\\\\192.168.1.15\\sadam\\lateamountPerWeek.jasper";
                    Map<String,Object> para = new HashMap<String,Object>();
                    para.put("date", datee);
                    para.put("week", dayOfWeek);
                    JasperPrint j = JasperFillManager.fillReport(in, para,DBConnect.con);
                    JasperViewer.viewReport(j,false);
                }
                catch (JRException ex) {
                } finally {
                }
                
                
            }
            catch (ParseException ex) {
        Logger.getLogger(latedayperweek.class.getName()).log(Level.SEVERE, null, ex);
            }
        

    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a3;
    private javax.swing.JLabel date1;
    public javax.swing.JTextField day1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField month1;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s8;
    private javax.swing.JLabel s9;
    private javax.swing.JButton save;
    public javax.swing.JTextField year1;
    // End of variables declaration//GEN-END:variables
      
}
