/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */
public final class people extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
        
    PreparedStatement pst ;
    ResultSet rs;
     public String y ;
     public String check;
      public String datee;
      public  Calendar cal;
      public String pphone1;
      public String pphone2;
      public String ppp2;
      public String ppp1;
      public String ttt1;
      public String ttt2;
      String dayyy ;
      
      
    
   
    public people() throws ParseException {
        initComponents();
        

         clear();
        check="true";
        comboxfromcombo3();
        
           cal = new GregorianCalendar();
             
                int month=cal.get(Calendar.MONTH)+1;
             int year = cal.get(Calendar.YEAR);
                 int dayy =cal.get(Calendar.DAY_OF_MONTH);
             dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
           date1.setText(year+"-"+month+"-"+dayyy);
           datee=date1.getText().toString();
 
         name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         phone.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
         address.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        cmvisa = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setText("اسم الشخص");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 70, 140, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel10.setText("العنوان");
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 80, -1));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 190, 30));

        save.setBackground(new java.awt.Color(138, 203, 195));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setText("حفظ");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel10.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 180, 40));

        address.setColumns(20);
        address.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 270, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setText("رقم ثاني");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 90, 30));

        phone2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 190, 30));

        phone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 190, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel32.setText("النوع");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 80, 40));

        cmvisa.setEditable(true);
        cmvisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "شنطة", "شهرية", "شنطه و شهرية", " " }));
        jPanel10.add(cmvisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 120, 30));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel24.setText("المبلغ");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 80, 30));

        amount.setEditable(false);
        amount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        amount.setText("0");
        jPanel10.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 70, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setText("رقم التليفون");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 120, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        serial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        serial.setForeground(new java.awt.Color(255, 255, 255));
        serial.setText("Serial");
        jPanel10.add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 160, 40));

        date1.setText("date");
        jPanel10.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
 try
        {
             int amountt = Integer.parseInt(amount.getText());
             if( !name.getText().trim().isEmpty())
               {
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العمليه", "تاكيد العمليه", dialogButton);
                    if(dialogResult == 0) {
                    try {
               String namee = name.getText();
               String phonee = phone.getText();
               String phonee2 = phone2.getText();
               String adresss = address.getText();
               String type = cmvisa.getSelectedItem().toString();
               
               String sqll = "INSERT INTO hany.people (name,phone,phone2,address,type,amount) VALUES ('"+namee+"','"+phonee+"','"+phonee2+"','"+adresss+"','"+type+"','"+amountt+"')";
               pst = (PreparedStatement)DBConnect.con.prepareStatement(sqll);
               pst.execute();
               clear();
               JOptionPane.showMessageDialog(null, "تمت الاضافة");
           } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, ex);
           }
               }
                    else
         {
             JOptionPane.showMessageDialog(null, "تم الغاء العملية");
         }
               }
         else
         {
             JOptionPane.showMessageDialog(null, "ادخل الاسم");
         }
        }
 catch(Exception ex)
 {
      JOptionPane.showMessageDialog(null, "ادخل رقم صحيح");
 }
         
         
          

              
                

    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox cmvisa;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField phone2;
    private javax.swing.JButton save;
    private javax.swing.JLabel serial;
    private javax.swing.JLabel serialid;
    // End of variables declaration//GEN-END:variables
public void clear()
{
    name.setText(""); 
    serialid.setText(""); 
 phone.setText("");
 address.setText("");
 phone2.setText("");
 amount.setText("0");
 cmvisa.setSelectedIndex(0);
}
 public void comboxfromcombo3()
      {
            cmvisa.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                JComboBox cmsupplier = (JComboBox) event.getSource();
                Object item = event.getItem();
                if(cmvisa.getSelectedItem().toString().equals("شهرية") || cmvisa.getSelectedItem().toString().equals("شنطه و شهرية"))
                {
                    amount.setEditable(true);
                }
                else
                {
                      amount.setEditable(false);
                }
        
         }
        });
       
      }
        
}
